[workspace]
members = ["crates/demo"]
resolver = "3"

[package]
name = "glazer"
version = "0.1.0"
edition = "2024"

[target.'cfg(target_os = "macos")'.dependencies]
objc2-foundation = "0.3.1"
objc2 = "0.6.2"
objc2-app-kit = "0.3.1"
